import { describe, expect, it } from 'vitest';
import { allocationTotal, clientSummary, durationMinutes, financialSummary, inheritedRate, remainingForSession, sessionAmounts } from './finance';
import { buildPublicReport } from './report';
import type { Client, Payment, PaymentAllocation, WorkSession } from '../types/domain';

const client = { id: 'c1', user_id: 'u1', name: 'Client', contact: null, email: null, status: 'active', hourly_rate: 15, payment_method: null, private_notes: 'secret', last_contact_date: null, next_follow_up_date: null, created_at: '' } as Client;
const session = { id: 's1', user_id: 'u1', client_id: 'c1', project_id: null, title: 'Configuration', session_date: '2026-07-15', started_at: null, ended_at: null, duration_minutes: 120, is_running: false, public_description: 'Configuration publique\navec détail', private_notes: 'Ne jamais exporter', hourly_rate: 15, commission_rate: 20, time_category: 'billable', gross_amount: 30, commission_amount: 6, net_amount: 24, created_at: '' } as WorkSession;
describe('règles freelance', () => {
  it('calcule durée, priorité de tarif et commission', () => { expect(durationMinutes('2026-07-15T10:00:00Z', '2026-07-15T11:30:00Z')).toBe(90); expect(inheritedRate(20, { hourly_rate: 18 }, { hourly_rate: 15 }, 12)).toBe(20); expect(inheritedRate(null, { hourly_rate: null }, { hourly_rate: 15 }, 12)).toBe(15); expect(sessionAmounts(300, 12, 20)).toEqual({ gross: 60, commission: 12, net: 48 }); });
  it('centralise le reste à recevoir : valorisé moins reçu', () => { const allocations = [{ id: 'a1', user_id: 'u1', payment_id: 'p1', work_session_id: 's1', allocated_amount: 10 }] as PaymentAllocation[]; const payment = { id: 'p1', user_id: 'u1', client_id: 'c1', project_id: null, payment_date: '2026-07-15', amount_expected: 30, amount_received: 10, fees: 1, payment_method: null, reference_note: '', status: 'partial', created_at: '' } as Payment; expect(allocationTotal('s1', allocations)).toBe(10); expect(remainingForSession(session, allocations)).toBe(20); expect(clientSummary('c1', [session], [payment], allocations)).toMatchObject({ generated: 30, received: 10, covered: 10, remaining: 20 }); expect(financialSummary([session], [payment], allocations)).toMatchObject({ valued: 30, received: 10, allocated: 10, remaining: 20 }); });
  it('ne fournit au rapport que les champs publics et conserve les retours à la ligne', () => { const report = buildPublicReport({ user_id: 'u1', display_name: 'Rayzk', public_site: 'rayzk.fr', default_hourly_rate: 12, currency: 'EUR', day_rollover_hour: 5 }, client, undefined, [session], { period: 'juillet', includeDurations: true, includeRate: false, includeAmounts: true }); expect(JSON.stringify(report)).toContain('Configuration publique\\navec détail'); expect(JSON.stringify(report)).not.toContain('Ne jamais exporter'); expect(JSON.stringify(report)).not.toContain('secret'); expect(report.generatedAt).toMatch(/^\d{2}\/\d{2}\/\d{4}$/); });
});
