import type { Client, Payment, PaymentAllocation, Project, WorkSession } from '../types/domain';

export function durationMinutes(startedAt: string | null, endedAt: string | null, fallback: number | null = null) { if (fallback !== null) return Math.max(0, Math.round(fallback)); if (!startedAt || !endedAt) return 0; return Math.max(0, Math.round((new Date(endedAt).getTime() - new Date(startedAt).getTime()) / 60_000)); }
export function inheritedRate(sessionRate: number | null | undefined, project: Pick<Project, 'hourly_rate'> | null | undefined, client: Pick<Client, 'hourly_rate'> | null | undefined, globalRate: number) { return sessionRate ?? project?.hourly_rate ?? client?.hourly_rate ?? globalRate; }
export function sessionAmounts(minutes: number, rate: number, commissionRate = 0, category: WorkSession['time_category'] = 'billable') { const gross = category === 'billable' ? Math.round((minutes / 60) * rate * 100) / 100 : 0; const commission = Math.round(gross * (commissionRate / 100) * 100) / 100; return { gross, commission, net: Math.round((gross - commission) * 100) / 100 }; }
export function allocationTotal(sessionId: string, allocations: PaymentAllocation[]) { return allocations.filter((item) => item.work_session_id === sessionId).reduce((sum, item) => sum + Number(item.allocated_amount), 0); }
export function remainingForSession(session: WorkSession, allocations: PaymentAllocation[]) { return Math.max(0, Number(session.gross_amount) - allocationTotal(session.id, allocations)); }
export function clientSummary(clientId: string, sessions: WorkSession[], payments: Payment[], allocations: PaymentAllocation[]) { const relevant = sessions.filter((item) => item.client_id === clientId && !item.is_running && item.time_category === 'billable'); const generated = relevant.reduce((sum, item) => sum + Number(item.gross_amount), 0); const net = relevant.reduce((sum, item) => sum + Number(item.net_amount), 0); const received = payments.filter((item) => item.client_id === clientId && item.status !== 'cancelled').reduce((sum, item) => sum + Number(item.amount_received), 0); const covered = relevant.reduce((sum, item) => sum + allocationTotal(item.id, allocations), 0); const minutes = relevant.reduce((sum, item) => sum + Number(item.duration_minutes || 0), 0); return { generated, net, received, covered, remaining: Math.max(0, generated - received), minutes, realHourlyRate: minutes ? net / (minutes / 60) : 0 }; }
export function financialSummary(sessions: WorkSession[], payments: Payment[], allocations: PaymentAllocation[]) { const relevant = sessions.filter((item) => !item.is_running && item.time_category === 'billable'); const valued = relevant.reduce((sum, item) => sum + Number(item.gross_amount), 0); const received = payments.filter((item) => item.status !== 'cancelled').reduce((sum, item) => sum + Number(item.amount_received), 0); const allocated = relevant.reduce((sum, item) => sum + allocationTotal(item.id, allocations), 0); return { valued, received, allocated, remaining: Math.max(0, valued - received) }; }
export function paymentStatus(expected: number, received: number, status: Payment['status']) { if (status === 'cancelled' || status === 'overdue' || status === 'requested' || status === 'planned') return status; if (received >= expected && expected > 0) return 'paid'; return received > 0 ? 'partial' : 'planned'; }
export function sessionPaymentState(session: WorkSession, allocations: PaymentAllocation[]) { const covered = allocationTotal(session.id, allocations); if (covered >= Number(session.gross_amount) && Number(session.gross_amount) > 0) return 'paid'; return covered > 0 ? 'partial' : 'unpaid'; }
export function lastProjectForClient(clientId: string, sessions: WorkSession[]) { return sessions.filter((session) => session.client_id === clientId && session.project_id).sort((a, b) => b.created_at.localeCompare(a.created_at))[0]?.project_id ?? null; }
export function projectsForClient(clientId: string, projects: Project[]) { return projects.filter((project) => project.client_id === clientId && project.status !== 'archived'); }
export function allocationPlan(sessions: WorkSession[], allocations: PaymentAllocation[], amount: number) {
  let available = Math.max(0, amount);
  return sessions.slice().sort((a, b) => a.session_date.localeCompare(b.session_date)).flatMap((session) => {
    const allocated = Math.min(available, remainingForSession(session, allocations));
    available -= allocated;
    return allocated > 0 ? [{ workSessionId: session.id, amount: allocated }] : [];
  });
}

export function paymentBreakdown(payment: Payment, allocations: PaymentAllocation[]) { const allocated = allocations.filter((item) => item.payment_id === payment.id).reduce((sum, item) => sum + Number(item.allocated_amount), 0); return { allocated, unallocated: Math.max(0, Number(payment.amount_received) - allocated) }; }
export function canSetSessionAmount(nextGrossAmount: number, alreadyAllocated: number) { return Number(nextGrossAmount) >= Number(alreadyAllocated); }
export function deterministicAllocationPlan(sessions: WorkSession[], payments: Payment[]) { const planned: Array<{ paymentId: string; workSessionId: string; amount: number }> = []; const occupied = new Map<string, number>(); for (const payment of payments.filter((item) => item.status !== 'cancelled').slice().sort((a, b) => a.payment_date.localeCompare(b.payment_date) || a.created_at.localeCompare(b.created_at) || a.id.localeCompare(b.id))) { let available = Number(payment.amount_received); for (const session of sessions.filter((item) => !item.is_running && item.time_category === 'billable').slice().sort((a, b) => a.session_date.localeCompare(b.session_date) || a.created_at.localeCompare(b.created_at) || a.id.localeCompare(b.id))) { const amount = Math.min(available, Math.max(0, Number(session.gross_amount) - Number(occupied.get(session.id) ?? 0))); if (amount > 0) { planned.push({ paymentId: payment.id, workSessionId: session.id, amount }); occupied.set(session.id, Number(occupied.get(session.id) ?? 0) + amount); available -= amount; } if (available <= 0) break; } } return planned; }
