import { useState } from 'react';
import { Download, LogOut, Save } from 'lucide-react';
import { useAppData } from '../../app/AppDataProvider';

export function SettingsPage({ onSignOut }: { onSignOut: () => void }) {
  const data = useAppData();
  const [name, setName] = useState(data.settings?.display_name || 'Rayzk');
  const [site, setSite] = useState(data.settings?.public_site || 'rayzk.fr');
  const [rate, setRate] = useState(String(data.settings?.default_hourly_rate || 12));
  const [rollover, setRollover] = useState(String(data.settings?.day_rollover_hour ?? 5));
  const save = () => void data.update('app_settings', data.userId, { display_name: name || 'Rayzk', public_site: site || 'rayzk.fr', default_hourly_rate: Number(rate || 12), day_rollover_hour: Math.max(0, Math.min(8, Number(rollover || 5))) });
  const exportJson = () => { const payload = { exported_at: new Date().toISOString(), data: { habits: data.habits, habit_entries: data.habitEntries, daily_notes: data.dailyNotes, clients: data.clients, projects: data.projects, work_sessions: data.sessions, payments: data.payments, payment_allocations: data.allocations, tasks: data.tasks, purchases: data.purchases, settings: data.settings } }; const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `rayzk-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); };
  return <section className="page settings-page"><div className="page-intro"><div><p className="eyebrow">Réglages</p><h1>Préférences et sauvegarde.</h1></div></div><section className="panel settings-form"><div className="form-grid"><label className="field"><span>Nom affiché</span><input value={name} onChange={(event) => setName(event.target.value)}/></label><label className="field"><span>Site affiché</span><input value={site} onChange={(event) => setSite(event.target.value)}/></label><label className="field"><span>Tarif horaire global (€)</span><input type="number" min="0" step="0.01" value={rate} onChange={(event) => setRate(event.target.value)}/></label><label className="field"><span>Changement de jour</span><select value={rollover} onChange={(event) => setRollover(event.target.value)}>{Array.from({ length: 9 }, (_, hour) => <option value={hour} key={hour}>{String(hour).padStart(2, '0')}:00</option>)}</select></label><p className="form-hint">Les habitudes et les nouvelles sessions saisies avant cette heure sont rattachées à la veille.</p><button className="button primary" onClick={save}><Save size={16}/> Enregistrer</button></div></section><section className="panel export-panel"><p className="eyebrow">Sauvegarde</p><h2>Export complet</h2><p>Le fichier JSON contient vos données personnelles et peut être conservé avant une migration. La restauration se fait actuellement manuellement dans Supabase.</p><button className="button subtle" onClick={exportJson}><Download size={16}/> Télécharger l’export JSON</button></section><button className="button brick" onClick={onSignOut}><LogOut size={16}/> Se déconnecter</button></section>;
}
