import { Pencil, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { useAppData } from '../../app/AppDataProvider';
import { euro } from '../../lib/format';
import type { Payment, WorkSession } from '../../types/domain';
import { Modal } from '../../components/ui/Modal';
import { SessionDetailsModal } from './SessionDetailsModal';

export function PaymentDetailsModal({ payment: initialPayment, onClose }: { payment: Payment; onClose: () => void }) {
  const data = useAppData(); const [editing, setEditing] = useState(false); const [confirming, setConfirming] = useState(false); const [selectedSession, setSelectedSession] = useState<WorkSession | null>(null); const [amount, setAmount] = useState(String(initialPayment.amount_received)); const [date, setDate] = useState(initialPayment.payment_date); const [error, setError] = useState<string | null>(null);
  const payment = data.payments.find((item) => item.id === initialPayment.id) ?? initialPayment; const allocations = data.allocations.filter((item) => item.payment_id === payment.id); const allocated = allocations.reduce((sum, item) => sum + Number(item.allocated_amount), 0); const unallocated = Math.max(0, Number(payment.amount_received) - allocated);
  const update = async () => { const nextAmount = Number(amount); if (!Number.isFinite(nextAmount) || nextAmount <= 0) { setError('Saisissez un montant positif.'); return; } setError(null); try { await data.manage('update_payment_and_rebuild_allocations', { p_payment_id: payment.id, p_amount: nextAmount, p_payment_date: date }); setEditing(false); } catch { setError('Le règlement n’a pas pu être modifié.'); } };
  const remove = async () => { setError(null); try { await data.manage('delete_payment_and_rebuild_allocations', { p_payment_id: payment.id }); onClose(); } catch { setError('Le règlement n’a pas pu être supprimé.'); } };
  return <>{<Modal title={editing ? 'Modifier le règlement' : 'Détail du règlement'} onClose={onClose}>{editing ? <form className="form-grid" onSubmit={(event) => { event.preventDefault(); void update(); }}><label className="field"><span>Montant reçu (€)</span><input autoFocus type="number" min="0.01" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)}/></label><label className="field"><span>Date</span><input type="date" value={date} onChange={(event) => setDate(event.target.value)}/></label>{error && <p className="form-hint">{error}</p>}<div className="button-row"><button type="button" className="button subtle" disabled={data.saving} onClick={() => setEditing(false)}>Annuler</button><button disabled={data.saving} className="button primary">{data.saving ? 'Enregistrement…' : 'Enregistrer'}</button></div></form> : <section className="detail-stack"><div><p className="eyebrow">{payment.payment_date}</p><h3>Règlement de {euro(Number(payment.amount_received))}</h3></div><div className="allocation-history">{allocations.length ? allocations.map((allocation) => { const session = data.sessions.find((item) => item.id === allocation.work_session_id); return <button key={allocation.id} className="allocation-row" onClick={() => session && setSelectedSession(session)} disabled={!session}><span><b>{session?.title || 'Session supprimée'}</b><small>{session?.session_date || '—'}</small></span><strong>{euro(Number(allocation.allocated_amount))}</strong></button>; }) : <p>Aucune session attribuée.</p>}<p className="unallocated">Non attribué : {euro(unallocated)}</p></div>{error && <p className="form-hint">{error}</p>}<div className="button-row"><button className="button subtle" onClick={() => setEditing(true)}><Pencil size={16}/> Modifier le règlement</button><button className="button brick" onClick={() => setConfirming(true)}><Trash2 size={16}/> Supprimer le règlement</button></div>{confirming && <section className="danger-confirm"><p><b>Supprimer ce règlement ?</b></p><p>Ses allocations seront supprimées puis reconstruites à partir des règlements restants.</p><div className="button-row"><button className="button subtle" disabled={data.saving} onClick={() => setConfirming(false)}>Annuler</button><button className="button brick" disabled={data.saving} onClick={() => void remove()}>{data.saving ? 'Suppression…' : 'Confirmer la suppression'}</button></div></section>}</section>}</Modal>}{selectedSession && <SessionDetailsModal session={selectedSession} onClose={() => setSelectedSession(null)}/>}</>;
}
