import { useMemo, useState } from 'react';
import { Document, Page, StyleSheet, Text, View, PDFDownloadLink } from '@react-pdf/renderer';
import { FileDown } from 'lucide-react';
import { useAppData } from '../../app/AppDataProvider';
import { buildPublicReport, type PublicReport } from '../../lib/report';
import { euro } from '../../lib/format';
import { Empty } from '../../components/ui/Modal';
const pdfStyles = StyleSheet.create({ page: { padding: 42, fontFamily: 'Helvetica', color: '#202420', fontSize: 10 }, title: { fontSize: 22, marginBottom: 6 }, muted: { color: '#666', marginBottom: 14 }, row: { borderBottom: '1 solid #ddd', paddingVertical: 9 }, total: { marginTop: 18, fontSize: 14, fontFamily: 'Helvetica-Bold' } });
function ReportDocument({ report }: { report: PublicReport }) { return <Document><Page size="A4" style={pdfStyles.page}><Text style={pdfStyles.title}>{report.issuer} · Rapport d’activité</Text><Text style={pdfStyles.muted}>{report.site} · {report.client}{report.project ? ` · ${report.project}` : ''}</Text><Text style={pdfStyles.muted}>Période : {report.period} · Généré le {report.generatedAt}</Text>{report.sessions.map((session, index) => <View style={pdfStyles.row} key={index}><Text>{session.date}{session.project ? ` · ${session.project}` : ''}</Text><Text>{session.description}</Text>{report.includeDurations && <Text>Durée : {session.duration}</Text>}{report.includeRate && <Text>Tarif : {euro(session.rate)} / h</Text>}{report.includeAmounts && <Text>Montant : {euro(session.amount)}</Text>}</View>)}<Text style={pdfStyles.total}>{report.sessions.length} session(s) · Durée totale : {report.totalDuration}{report.includeAmounts ? ` · Total : ${euro(report.total)}` : ''}</Text></Page></Document>; }
export function ReportPanel({ clientId, projectId }: { clientId: string; projectId?: string }) {
  const { clients, projects, sessions, settings } = useAppData(); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [selected, setSelected] = useState<string[] | null>(null); const [durations, setDurations] = useState(true); const [rate, setRate] = useState(false); const [amounts, setAmounts] = useState(true);
  const client = clients.find((item) => item.id === clientId); const project = projects.find((item) => item.id === projectId); const available = sessions.filter((item) => item.client_id === clientId && !item.is_running && (!projectId || item.project_id === projectId) && (!from || item.session_date >= from) && (!to || item.session_date <= to)); const picked = selected === null ? available : available.filter((item) => selected.includes(item.id)); const report = useMemo(() => client ? buildPublicReport(settings, client, project, picked, { period: from || to ? `${from || '…'} au ${to || '…'}` : 'Toutes les sessions sélectionnées', includeDurations: durations, includeRate: rate, includeAmounts: amounts }) : null, [amounts, client, durations, from, picked, project, rate, settings, to]);
  if (!client || !report) return null; const toggle = (id: string) => setSelected((current) => (current ?? available.map((item) => item.id)).includes(id) ? (current ?? available.map((item) => item.id)).filter((value) => value !== id) : [...(current ?? available.map((item) => item.id)), id]);
  return <section className="report-panel report-v053"><header><p className="eyebrow">Étape 1</p><h3>Sessions et période</h3></header><div className="field-row"><label className="field"><span>Date de début</span><input type="date" value={from} onChange={(event) => setFrom(event.target.value)}/></label><label className="field"><span>Date de fin</span><input type="date" value={to} onChange={(event) => setTo(event.target.value)}/></label></div><div className="report-select-actions"><button className="text-link" onClick={() => setSelected(null)}>Tout sélectionner</button><button className="text-link" onClick={() => setSelected([])}>Tout désélectionner</button></div>{available.length ? <div className="report-sessions">{available.map((item) => <button className={`report-session-choice ${(selected === null || selected.includes(item.id)) ? 'selected' : ''}`} key={item.id} onClick={() => toggle(item.id)}><span><b>{item.session_date} · {item.title || 'Session de travail'}</b><small>{item.project_id ? projects.find((value) => value.id === item.project_id)?.name : 'Sans mission'} · {item.duration_minutes} min · {euro(Number(item.gross_amount))}</small></span><i/></button>)}</div> : <Empty>Aucune session dans cette période.</Empty>}<header><p className="eyebrow">Étape 2</p><h3>Contenu du PDF</h3></header><div className="report-options custom-toggles"><Toggle checked={durations} onChange={setDurations} label="Afficher la durée de chaque session"/><Toggle checked={rate} onChange={setRate} label="Afficher le tarif horaire appliqué" detail="Ajoute le tarif utilisé à côté de chaque session."/><Toggle checked={amounts} onChange={setAmounts} label="Afficher le montant de chaque session"/></div><div className="report-preview"><p className="eyebrow">Aperçu avant génération</p><strong>{report.issuer} · {report.site}</strong><p>{report.client}{report.project ? ` · ${report.project}` : ''} · {report.period}</p>{report.sessions.map((item, index) => <p key={index}><b>{item.date}</b> · {item.description} {durations ? `· ${item.duration}` : ''}{amounts ? ` · ${euro(item.amount)}` : ''}</p>)}<p><b>{report.sessions.length} session(s) · {report.totalDuration}{amounts ? ` · ${euro(report.total)}` : ''}</b></p></div>{picked.length > 0 && <PDFDownloadLink document={<ReportDocument report={report}/>} fileName={`rapport-${client.name.toLowerCase().replace(/\s+/g, '-')}.pdf`} className="button primary">{({ loading }) => <><FileDown size={16}/> {loading ? 'Préparation…' : 'Télécharger le PDF'}</>}</PDFDownloadLink>}</section>;
}
function Toggle({ checked, onChange, label, detail }: { checked: boolean; onChange: (value: boolean) => void; label: string; detail?: string }) { return <button className={`custom-toggle ${checked ? 'selected' : ''}`} onClick={() => onChange(!checked)}><i/ ><span><b>{label}</b>{detail && <small>{detail}</small>}</span></button>; }
