import { Pencil, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { useAppData } from '../../app/AppDataProvider';
import { allocationTotal, remainingForSession, sessionPaymentState } from '../../lib/finance';
import { euro, minutesLabel } from '../../lib/format';
import type { WorkSession } from '../../types/domain';
import { SessionForm } from '../../components/ui/Forms';
import { Modal, Status } from '../../components/ui/Modal';

export function SessionDetailsModal({ session: initialSession, onClose }: { session: WorkSession; onClose: () => void }) {
  const data = useAppData(); const [editing, setEditing] = useState(false); const [confirming, setConfirming] = useState(false); const [error, setError] = useState<string | null>(null);
  const session = data.sessions.find((item) => item.id === initialSession.id) ?? initialSession; const client = data.clients.find((item) => item.id === session.client_id); const project = data.projects.find((item) => item.id === session.project_id); const covered = allocationTotal(session.id, data.allocations); const remaining = remainingForSession(session, data.allocations); const payment = sessionPaymentState(session, data.allocations); const time = [session.started_at, session.ended_at].filter(Boolean).map((item) => new Date(item as string).toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' })).join(' → ');
  const remove = async () => { setError(null); try { await data.manage('delete_work_session_and_rebuild_allocations', { p_session_id: session.id }); onClose(); } catch { setError('La session n’a pas pu être supprimée.'); } };
  if (editing) return <Modal title="Modifier la session" onClose={() => setEditing(false)}><SessionForm session={session} lockClient onDone={() => setEditing(false)}/></Modal>;
  return <Modal title="Détail de la session" onClose={onClose}><section className="detail-stack"><div><p className="eyebrow">{session.session_date}</p><h3>{session.title}</h3><p className="session-copy">{session.public_description || 'Aucune description publique.'}</p></div><dl className="detail-grid"><div><dt>Client</dt><dd>{client?.name || 'Client'}</dd></div><div><dt>Mission</dt><dd>{project?.name || 'Sans mission'}</dd></div><div><dt>Durée</dt><dd>{minutesLabel(Number(session.duration_minutes || 0))}</dd></div><div><dt>Catégorie</dt><dd>{session.time_category === 'billable' ? 'Facturable' : 'Apprentissage / recherche'}</dd></div>{time && <div><dt>Heures</dt><dd>{time}</dd></div>}<div><dt>Tarif enregistré</dt><dd>{euro(Number(session.hourly_rate))} / h</dd></div><div><dt>Valeur du travail</dt><dd>{euro(Number(session.gross_amount))}</dd></div>{Number(session.commission_rate) > 0 && <><div><dt>Commission</dt><dd>{session.commission_rate} % · −{euro(Number(session.commission_amount))}</dd></div><div><dt>Net personnel</dt><dd>{euro(Number(session.net_amount))}</dd></div></>}</dl><section className="detail-payment"><div><span>Statut de paiement</span><Status>{payment === 'paid' ? 'Payée' : payment === 'partial' ? 'Partiellement payée' : 'Non payée'}</Status></div><p>{euro(covered)} couvert · {euro(remaining)} restant</p></section>{session.private_notes && <section className="private-notes"><p className="eyebrow">Note privée</p><p className="session-copy">{session.private_notes}</p></section>}{error && <p className="form-hint">{error}</p>}<div className="button-row"><button className="button subtle" onClick={() => setEditing(true)}><Pencil size={16}/> Modifier la session</button><button className="button brick" onClick={() => setConfirming(true)}><Trash2 size={16}/> Supprimer définitivement</button></div>{confirming && <section className="danger-confirm"><p><b>Supprimer définitivement « {session.title} » ?</b></p><p>{session.session_date} · {minutesLabel(Number(session.duration_minutes || 0))} · {euro(Number(session.gross_amount))}</p>{covered > 0 && <p>Cette session possède {euro(covered)} attribués. Les règlements seront conservés et les allocations seront recalculées sur les autres sessions du client.</p>}<div className="button-row"><button className="button subtle" disabled={data.saving} onClick={() => setConfirming(false)}>Annuler</button><button className="button brick" disabled={data.saving} onClick={() => void remove()}>{data.saving ? 'Suppression…' : 'Confirmer la suppression'}</button></div></section>}</section></Modal>;
}
